import arcade

SCREEN_WIDTH = 900
SCREEN_HEIGHT = 900
SCREEN_TITLE = "Hierachical anticipatory models"

NUM_ROBOTS = 2

CRATE_GRID_SIZE = 30
MAXIMUM_GRID_X = CRATE_GRID_SIZE
MAXIMUM_GRID_Y = CRATE_GRID_SIZE
GRID_RATIO_X = 1 * SCREEN_WIDTH / MAXIMUM_GRID_X
GRID_RATIO_Y = 1 * SCREEN_HEIGHT / MAXIMUM_GRID_Y

CRATES: dict[(int, int), any] = {}
ROBOTS = arcade.SpriteList()
